version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'  # Expose backend on port 5000
    depends_on:
      - mongo  # Ensure mongo service is ready before starting backend
    networks:
      - app-network
  mongo:
    image: mongo
    ports:
      - '27017:27017'  # Expose mongo on port 27017
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'  # Expose frontend on port 3000
    networks:
      - app-network
networks:
  app-network:
    driver: bridge